name: 'PrePost' 
description: 'Simple action with Pre and Post scripts'
author: 'Louis-Guillaume MORAND' 
runs:
  using: 'node12' 
  main: 'index.js'
  pre: 'pre.js'
  pre-if: 'runner.os != linux'
  post: 'post.js'
  
branding:
  icon: 'message-circle'  
  color: 'orange' 
