name: 'PrePost' 
description: 'Simple action with Pre and Post scripts'
author: 'Louis-Guillaume MORAND' 
runs:
  using: 'node16' 
  main: 'index.js'
  pre: 'pre.js'
  pre-if: runner.os == 'linux'
  post: 'post.js'
  post-if: 'success()'
branding:
  icon: 'message-circle'  
  color: 'orange' 
